wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1717162072
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      4: 3.8.19
      5: 0.17.0
      8:
      - 5
      13: linux-x86_64
data:
  desc: null
  value: Chinese
data_num:
  desc: null
  value: 1845
label_num:
  desc: null
  value: 30
hidden_dim:
  desc: null
  value: 4
embedding_dim:
  desc: null
  value: 8
batch_size:
  desc: null
  value: 256
learning_rate:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: SGD
